INSERT INTO users (USER_ID, USER_EMAIL, USER_NICK, USER_PHONE, USER_DEVICE_TOKEN) VALUES
                                                                                      ('user1', 'user1@example.com', 'User One', '010-1234-5678', 'deviceToken1'),
                                                                                      ('user2', 'user2@example.com', 'User Two', NULL, 'deviceToken2'),
                                                                                      ('user3', 'user3@example.com', 'User Three', '010-8765-4321', NULL),
                                                                                      ('user4', 'user4@example.com', 'User Four', NULL, NULL),
                                                                                      ('user5', 'user5@example.com', 'User Five', '010-1122-3344', 'deviceToken5');

INSERT INTO ticket (ticket_id, arrive_time, depart_date, depart_time, price, ticket_type, arrive_station, depart_station)
VALUES
    (1, '0810', '20241009', '0508', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산'),
    (2, '1105', '20241009', '0544', '27600원', '무궁화호', '여수EXPO', '용산'),
    (3, '1019', '20241009', '0710', '47200원', 'KTX', '여수EXPO', '용산'),
    (4, '1156', '20241009', '0714', '41100원', 'ITX-새마을', '여수EXPO', '용산'),
    (5, '1123', '20241009', '0743', '46000원', 'KTX', '여수EXPO', '용산'),
    (6, '1146', '20241009', '0840', '47200원', 'KTX', '여수EXPO', '용산'),
    (7, '1513', '20241009', '0938', '27600원', '무궁화호', '여수EXPO', '용산'),
    (8, '1426', '20241009', '0947', '0원', 'ITX-마음', '여수EXPO', '용산'),
    (9, '1303', '20241009', '0953', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산'),
    (10, '1401', '20241009', '1053', '47200원', 'KTX', '여수EXPO', '용산'),
    (11, '1521', '20241009', '1218', '47200원', 'KTX-산천(A-type)', '여수EXPO', '용산'),
    (12, '1543', '20241009', '1245', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산'),
    (13, '1710', '20241009', '1410', '47200원', 'KTX', '여수EXPO', '용산'),
    (14, '1828', '20241009', '1438', '46000원', 'KTX-산천(A-type)', '여수EXPO', '용산'),
    (15, '2020', '20241009', '1504', '27600원', '무궁화호', '여수EXPO', '용산'),
    (16, '2122', '20241009', '1638', '41100원', 'ITX-새마을', '여수EXPO', '용산'),
    (17, '1954', '20241009', '1643', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산'),
    (18, '2143', '20241009', '1718', '0원', 'ITX-마음', '여수EXPO', '용산'),
    (19, '2042', '20241009', '1744', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산'),
    (20, '2151', '20241009', '1848', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산'),
    (21, '0026', '20241010', '1915', '27600원', '무궁화호', '여수EXPO', '용산'),
    (22, '2309', '20241009', '2008', '47200원', 'KTX', '여수EXPO', '용산'),
    (23, '2335', '20241009', '2033', '47200원', 'KTX-산천(A-type)', '여수EXPO', '용산'),
    (24, '0035', '20241010', '2148', '47200원', 'KTX-산천(B-type)', '여수EXPO', '용산');


-- book_mark 테이블에 더미 데이터 삽입
INSERT INTO book_mark (is_sent, want_first_class, want_normal_seat, want_baby_seat, want_waiting_reservation, ticket_id, USER_ID) VALUES
-- user1의 북마크 20개
(true, true, 'SEAT', 'NOTFOUND', false, 1, 'user1'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 2, 'user1'),
(true, true, 'NOTFOUND', 'STANDING_SEAT', false, 3, 'user1'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 4, 'user1'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 5, 'user1'),
(false, false, 'NOTFOUND', 'SEAT', true, 6, 'user1'),
(true, true, 'SEAT', 'SEAT', false, 7, 'user1'),
(false, false, 'STANDING_SEAT', 'STANDING_SEAT', true, 8, 'user1'),
(true, true, 'NOTFOUND', 'SEAT', false, 9, 'user1'),
(false, false, 'SEAT', 'NOTFOUND', true, 10, 'user1'),
(true, true, 'STANDING_SEAT', 'SEAT', false, 11, 'user1'),
(false, false, 'NOTFOUND', 'STANDING_SEAT', true, 12, 'user1'),
(true, true, 'SEAT', 'STANDING_SEAT', false, 13, 'user1'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 14, 'user1'),
(true, true, 'NOTFOUND', 'SEAT', false, 15, 'user1'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 16, 'user1'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 17, 'user1'),
(false, false, 'NOTFOUND', 'SEAT', true, 18, 'user1'),
(true, true, 'SEAT', 'STANDING_SEAT', false, 19, 'user1'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 20, 'user1'),

-- user2의 북마크 20개
(true, true, 'SEAT', 'STANDING_SEAT', false, 1, 'user2'),
(false, false, 'NOTFOUND', 'SEAT', true, 2, 'user2'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 3, 'user2'),
(false, false, 'SEAT', 'SEAT', true, 4, 'user2'),
(true, true, 'NOTFOUND', 'STANDING_SEAT', false, 5, 'user2'),
(false, false, 'SEAT', 'NOTFOUND', true, 6, 'user2'),
(true, true, 'STANDING_SEAT', 'SEAT', false, 7, 'user2'),
(false, false, 'NOTFOUND', 'STANDING_SEAT', true, 8, 'user2'),
(true, true, 'SEAT', 'NOTFOUND', false, 9, 'user2'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 10, 'user2'),
(true, true, 'NOTFOUND', 'SEAT', false, 11, 'user2'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 12, 'user2'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 13, 'user2'),
(false, false, 'NOTFOUND', 'SEAT', true, 14, 'user2'),
(true, true, 'SEAT', 'STANDING_SEAT', false, 15, 'user2'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 16, 'user2'),
(true, true, 'NOTFOUND', 'SEAT', false, 17, 'user2'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 18, 'user2'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 19, 'user2'),
(false, false, 'NOTFOUND', 'SEAT', true, 20, 'user2'),

-- user3의 북마크 20개
(true, true, 'STANDING_SEAT', 'SEAT', false, 1, 'user3'),
(false, false, 'SEAT', 'NOTFOUND', true, 2, 'user3'),
(true, true, 'NOTFOUND', 'STANDING_SEAT', false, 3, 'user3'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 4, 'user3'),
(true, true, 'SEAT', 'NOTFOUND', false, 5, 'user3'),
(false, false, 'NOTFOUND', 'SEAT', true, 6, 'user3'),
(true, true, 'STANDING_SEAT', 'STANDING_SEAT', false, 7, 'user3'),
(false, false, 'SEAT', 'SEAT', true, 8, 'user3'),
(true, true, 'NOTFOUND', 'SEAT', false, 9, 'user3'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 10, 'user3'),
(true, true, 'SEAT', 'STANDING_SEAT', false, 11, 'user3'),
(false, false, 'NOTFOUND', 'SEAT', true, 12, 'user3'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 13, 'user3'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 14, 'user3'),
(true, true, 'NOTFOUND', 'SEAT', false, 15, 'user3'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 16, 'user3'),
(true, true, 'SEAT', 'SEAT', false, 17, 'user3'),
(false, false, 'NOTFOUND', 'SEAT', true, 18, 'user3'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 19, 'user3'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 20, 'user3'),

-- user4의 북마크 20개
(true, true, 'NOTFOUND', 'SEAT', false, 1, 'user4'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 2, 'user4'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 3, 'user4'),
(false, false, 'NOTFOUND', 'SEAT', true, 4, 'user4'),
(true, true, 'SEAT', 'SEAT', false, 5, 'user4'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 6, 'user4'),
(true, true, 'NOTFOUND', 'STANDING_SEAT', false, 7, 'user4'),
(false, false, 'SEAT', 'SEAT', true, 8, 'user4'),
(true, true, 'STANDING_SEAT', 'SEAT', false, 9, 'user4'),
(false, false, 'NOTFOUND', 'SEAT', true, 10, 'user4'),
(true, true, 'SEAT', 'NOTFOUND', false, 11, 'user4'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 12, 'user4'),
(true, true, 'NOTFOUND', 'SEAT', false, 13, 'user4'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 14, 'user4'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 15, 'user4'),
(false, false, 'NOTFOUND', 'SEAT', true, 16, 'user4'),
(true, true, 'SEAT', 'SEAT', false, 17, 'user4'),
(false, false, 'STANDING_SEAT', 'NOTFOUND', true, 18, 'user4'),
(true, true, 'NOTFOUND', 'SEAT', false, 19, 'user4'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 20, 'user4'),

-- user5의 북마크 20개
(true, true, 'SEAT', 'STANDING_SEAT', false, 1, 'user5'),
(false, false, 'NOTFOUND', 'SEAT', true, 2, 'user5'),
(true, true, 'STANDING_SEAT', 'SEAT', false, 3, 'user5'),
(false, false, 'SEAT', 'NOTFOUND', true, 4, 'user5'),
(true, true, 'NOTFOUND', 'STANDING_SEAT', false, 5, 'user5'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 6, 'user5'),
(true, true, 'SEAT', 'SEAT', false, 7, 'user5'),
(false, false, 'NOTFOUND', 'SEAT', true, 8, 'user5'),
(true, true, 'STANDING_SEAT', 'NOTFOUND', false, 9, 'user5'),
(false, false, 'SEAT', 'STANDING_SEAT', true, 10, 'user5'),
(true, true, 'NOTFOUND', 'SEAT', false, 11, 'user5'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 12, 'user5'),
(true, true, 'SEAT', 'NOTFOUND', false, 13, 'user5'),
(false, false, 'NOTFOUND', 'SEAT', true, 14, 'user5'),
(true, true, 'STANDING_SEAT', 'SEAT', false, 15, 'user5'),
(false, false, 'SEAT', 'NOTFOUND', true, 16, 'user5'),
(true, true, 'NOTFOUND', 'SEAT', false, 17, 'user5'),
(false, false, 'STANDING_SEAT', 'SEAT', true, 18, 'user5'),
(true, true, 'SEAT', 'SEAT', false, 19, 'user5'),
(false, false, 'NOTFOUND', 'SEAT', true, 20, 'user5');
